### ISSUE TITLE
Update documentation and new idea

### ISSUE THREAD

**Issue by phaminhieuu** [mrcaidev/react-hooks#1]
Hi, mrcaidev.
I just pass by and very interested in your project. I've some problems about delaying useEffect after update state, currently I've to write my own custom hook, but I want it can be reused in every project and yeah, I found your library with useDelayEffect, very nice and clean. 
It would be better if you have a more detailed documentation of what custom hooks you did.
Hear some ideas I want to implement for your library:
1. The hook that can skip the first render of useEffect ( useEffect will render 2 times on mount as you know)
2. Hook can retrieve window dimensions every time we resize the window ( I usually write it by useContext, but the code is too long :))) )
Hope this helpful, thanks for your work

**Comment by mrcaidev** [comment]
Thank you for your advice!

---

> It would be better if you have a more detailed documentation of what custom hooks you did.

Yeah, of course!

I used to use [api-documenter](https://www.npmjs.com/package/@microsoft/api-documenter) to generate documentations automatically, but I found the output not that satisfactory, and then I removed it.

And then I forgot about the docs.😅 After that, I was working on other side projects and having courses in university at the same time. I apologize for that - hope it did not bring you many troubles when reading my codes!

And I'm learning monorepo pattern (with turborepo) right now, and I think it would help me structure this repo better, with docs. So I will try to integrate the doc and package within this repository, after I finished reading the turborepo docs.

---

> The hook that can skip the first render of useEffect (useEffect will render 2 times on mount as you know)

I did write this hook, before v0.1.0. I even wrote [a blog post about this](https://dev.to/mrcaidev/new-behavior-of-useeffect-in-react-18-dev-strict-mode-332i). You can see my implementation here, if you are interested.

**But I decided to remove the hook when publishing v0.1.0.** React Beta docs has [explained why in details](https://beta.reactjs.org/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development). This line hit me in particular:

> The right question isn’t “how to run an Effect once”, but “how to fix my Effect so that it works after remounting”.

I will probably bring this hook back, but I would name it like `useUnsafeOnceEffect`, etc.

---

> 2. Hook can retrieve window dimensions every time we resize the window.

Good idea! I guess I will add it right in the next version.

---

Again, thanks for your advice!
